### ISSUE TITLE
Random errors during concurrency tests

### ISSUE THREAD

**Issue by giovannipizzi** [giovannipizzi/disk-objectstore#25]
Here are two possible outputs:
```
2020-06-15T13:30:41.9365030Z         error_string = 'At least one of the concurrent processes failed!\nMessages:\n' + '\n'.join(error_messages)
2020-06-15T13:30:41.9365210Z >       assert len(error_messages) == 0, error_string
2020-06-15T13:30:41.9365750Z E       AssertionError: At least one of the concurrent processes failed!
2020-06-15T13:30:41.9365910Z E         Messages:
2020-06-15T13:30:41.9366050Z E         WORKER process #2 failed with error code 1!
2020-06-15T13:30:41.9366190Z E         WORKER 2 output:
2020-06-15T13:30:41.9366760Z E         [1176 2020-06-15-13:22:36] Currently known objects: 0 packed, 0 loose
2020-06-15T13:30:41.9367270Z E         [1176 2020-06-15-13:22:36] Pack objects on disk: 0
2020-06-15T13:30:41.9367800Z E         [1176 2020-06-15-13:22:36] Iteration 1/4, generating 100 files in memory...
2020-06-15T13:30:41.9368300Z E         [1176 2020-06-15-13:22:36] 200 object MD5s read from 2 files (with single-object reads).
2020-06-15T13:30:41.9368830Z E         [1176 2020-06-15-13:22:37] Iteration 2/4, generating 100 files in memory...
2020-06-15T13:30:41.9369370Z E         [1176 2020-06-15-13:22:37] 600 object MD5s read from 6 files (with single-object reads).
2020-06-15T13:30:41.9369900Z E         [1176 2020-06-15-13:22:39] Iteration 3/4, generating 100 files in memory...
2020-06-15T13:30:41.9370720Z E         [1176 2020-06-15-13:22:39] 1100 object MD5s read from 11 files (with single-object reads).
2020-06-15T13:30:41.9371370Z E         [1176 2020-06-15-13:22:43] Iteration 4/4, generating 100 files in memory...
2020-06-15T13:30:41.9371920Z E         [1176 2020-06-15-13:22:43] 1600 object MD5s read from 16 files (with single-object reads).
2020-06-15T13:30:41.9372100Z E         
2020-06-15T13:30:41.9372600Z E         ------------------------------------------------------------------------------
2020-06-15T13:30:41.9372760Z E         WORKER 2 error:
2020-06-15T13:30:41.9372900Z E         Traceback (most recent call last):
2020-06-15T13:30:41.9373430Z E           File "/Users/runner/runners/2.263.0/work/disk-objectstore/disk-objectstore/tests/concurrent_tests/periodic_worker.py", line 152, in <module>
2020-06-15T13:30:41.9373950Z E             main()  # pylint: disable=no-value-for-parameter
2020-06-15T13:30:41.9374530Z E           File "/Users/runner/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/click/core.py", line 829, in __call__
2020-06-15T13:30:41.9374730Z E             return self.main(*args, **kwargs)
2020-06-15T13:30:41.9375270Z E           File "/Users/runner/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/click/core.py", line 782, in main
2020-06-15T13:30:41.9375450Z E             rv = self.invoke(ctx)
2020-06-15T13:30:41.9376000Z E           File "/Users/runner/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
2020-06-15T13:30:41.9376170Z E             return ctx.invoke(self.callback, **ctx.params)
2020-06-15T13:30:41.9376780Z E           File "/Users/runner/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/click/core.py", line 610, in invoke
2020-06-15T13:30:41.9376950Z E             return callback(*args, **kwargs)
2020-06-15T13:30:41.9377610Z E           File "/Users/runner/runners/2.263.0/work/disk-objectstore/disk-objectstore/tests/concurrent_tests/periodic_worker.py", line 148, in main
2020-06-15T13:30:41.9377760Z E             assert retrieved_md5s == all_md5s
2020-06-15T13:30:41.9377900Z E         AssertionError
```

and

```
2020-06-15T12:36:55.1750560Z         error_string = 'At least one of the concurrent processes failed!\nMessages:\n' + '\n'.join(error_messages)
2020-06-15T12:36:55.1751210Z >       assert len(error_messages) == 0, error_string
2020-06-15T12:36:55.1751800Z E       AssertionError: At least one of the concurrent processes failed!
2020-06-15T12:36:55.1752390Z E         Messages:
2020-06-15T12:36:55.1752950Z E         WORKER process #3 failed with error code 1!
2020-06-15T12:36:55.1754490Z E         WORKER 3 output:
2020-06-15T12:36:55.1756330Z E         [1430 2020-06-15-12:34:23] Currently known objects: 0 packed, 18 loose
2020-06-15T12:36:55.1756930Z E         [1430 2020-06-15-12:34:23] Pack objects on disk: 0
2020-06-15T12:36:55.1757590Z E         [1430 2020-06-15-12:34:23] Iteration 1/4, generating 100 files in memory...
2020-06-15T12:36:55.1758170Z E         [1430 2020-06-15-12:34:23] 400 object MD5s read from 4 files (with bulk reads).
2020-06-15T12:36:55.1758730Z E         [1430 2020-06-15-12:34:24] Iteration 2/4, generating 100 files in memory...
2020-06-15T12:36:55.1759230Z E         [1430 2020-06-15-12:34:24] 800 object MD5s read from 8 files (with bulk reads).
2020-06-15T12:36:55.1759790Z E         [1430 2020-06-15-12:34:26] Iteration 3/4, generating 100 files in memory...
2020-06-15T12:36:55.1760910Z E         [1430 2020-06-15-12:34:26] 1100 object MD5s read from 11 files (with bulk reads).
2020-06-15T12:36:55.1761140Z E         
2020-06-15T12:36:55.1761700Z E         ------------------------------------------------------------------------------
2020-06-15T12:36:55.1761900Z E         WORKER 3 error:
2020-06-15T12:36:55.1762050Z E         Traceback (most recent call last):
2020-06-15T12:36:55.1762660Z E           File "/Users/runner/runners/2.263.0/work/disk-objectstore/disk-objectstore/tests/concurrent_tests/periodic_worker.py", line 152, in <module>
2020-06-15T12:36:55.1763310Z E             main()  # pylint: disable=no-value-for-parameter
2020-06-15T12:36:55.1763910Z E           File "/Users/runner/hostedtoolcache/Python/3.6.10/x64/lib/python3.6/site-packages/click/core.py", line 829, in __call__
2020-06-15T12:36:55.1764230Z E             return self.main(*args, **kwargs)
2020-06-15T12:36:55.1764780Z E           File "/Users/runner/hostedtoolcache/Python/3.6.10/x64/lib/python3.6/site-packages/click/core.py", line 782, in main
2020-06-15T12:36:55.1764980Z E             rv = self.invoke(ctx)
2020-06-15T12:36:55.1765550Z E           File "/Users/runner/hostedtoolcache/Python/3.6.10/x64/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
2020-06-15T12:36:55.1765760Z E             return ctx.invoke(self.callback, **ctx.params)
2020-06-15T12:36:55.1766320Z E           File "/Users/runner/hostedtoolcache/Python/3.6.10/x64/lib/python3.6/site-packages/click/core.py", line 610, in invoke
2020-06-15T12:36:55.1766520Z E             return callback(*args, **kwargs)
2020-06-15T12:36:55.1767110Z E           File "/Users/runner/runners/2.263.0/work/disk-objectstore/disk-objectstore/tests/concurrent_tests/periodic_worker.py", line 147, in main
2020-06-15T12:36:55.1767300Z E             retrieved_md5s[obj_uuid] = hashlib.md5(container.get_object_content(obj_uuid)).hexdigest()
2020-06-15T12:36:55.1767980Z E           File "/Users/runner/runners/2.263.0/work/disk-objectstore/disk-objectstore/disk_objectstore/container.py", line 288, in get_object_content
2020-06-15T12:36:55.1768180Z E             return handle.read()
2020-06-15T12:36:55.1768780Z E           File "/Users/runner/runners/2.263.0/work/disk-objectstore/disk-objectstore/disk_objectstore/utils.py", line 271, in read
2020-06-15T12:36:55.1769300Z E             next_chunk = self.read(size=self._CHUNKSIZE)
2020-06-15T12:36:55.1769870Z E           File "/Users/runner/runners/2.263.0/work/disk-objectstore/disk-objectstore/disk_objectstore/utils.py", line 304, in read
2020-06-15T12:36:55.1770420Z E             "There is no data in the reading buffer, but we didn't reach the end of "
2020-06-15T12:36:55.1771040Z E         ValueError: There is no data in the reading buffer, but we didn't reach the end of the compressed stream: there must be a problem in the incoming buffer
2020-06-15T12:36:55.1771230Z E         
2020-06-15T12:36:55.1771390Z E         ==============================================================================
2020-06-15T12:36:55.1771640Z E       assert 7 == 0
2020-06-15T12:36:55.1772380Z E        +  where 7 = len(['WORKER process #3 failed with error code 1!', 'WORKER 3 output:', '[1430 2020-06-15-12:34:23] Currently known object... buffer, but we didn\'t reach the end of the compressed stream: there must be a problem in the incoming buffer\n', ...])
2020-06-15T12:36:55.1772540Z 
2020-06-15T12:36:55.1772650Z tests/test_concurrency.py:80: AssertionError
```

**Comment by giovannipizzi** [comment]
Duplicate of #4
