### ISSUE TITLE
Concurrency issue on Mac OS X

### ISSUE THREAD

**Issue by giovannipizzi** [giovannipizzi/disk-objectstore#43]
After fixing #4, I got another error:

```
E         WARNING!!! b760efe69c5db5353704d2d47bb91c195775196b0744ae6633bd90ab5903df1e is b'' (<class 'bytes'>)
120
E         
121
E         ------------------------------------------------------------------------------
122
E         WORKER 1 error:
123
E         Traceback (most recent call last):
124
E           File "/Users/runner/work/disk-objectstore/disk-objectstore/tests/concurrent_tests/periodic_worker.py", line 192, in <module>
125
E             main()  # pylint: disable=no-value-for-parameter
126
E           File "/Users/runner/hostedtoolcache/Python/3.7.7/x64/lib/python3.7/site-packages/click/core.py", line 829, in __call__
127
E             return self.main(*args, **kwargs)
128
E           File "/Users/runner/hostedtoolcache/Python/3.7.7/x64/lib/python3.7/site-packages/click/core.py", line 782, in main
129
E             rv = self.invoke(ctx)
130
E           File "/Users/runner/hostedtoolcache/Python/3.7.7/x64/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
131
E             return ctx.invoke(self.callback, **ctx.params)
132
E           File "/Users/runner/hostedtoolcache/Python/3.7.7/x64/lib/python3.7/site-packages/click/core.py", line 610, in invoke
133
E             return callback(*args, **kwargs)
134
E           File "/Users/runner/work/disk-objectstore/disk-objectstore/tests/concurrent_tests/periodic_worker.py", line 159, in main
135
E             key, all_checksums[key], retrieved_checksums[key]
136
E         AssertionError: Mismatch for b760efe69c5db5353704d2d47bb91c195775196b0744ae6633bd90ab5903df1e: b760efe69c5db5353704d2d47bb91c195775196b0744ae6633bd90ab5903df1e vs. e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```
randomly, at least twice.

Apparently, there are still cases in which one gets empty data back. This needs to be investigated further.

**Comment by giovannipizzi** [comment]
Got again the same error on PR #49... (Mac, py3.7). I will need to check if I can reproduce it. For now I'll just rerun the tests.

**Comment by giovannipizzi** [comment]
Check the branch `check_concurrency` where I repeat the test 20 times (10 with packing and 10 without) to show the problem with higher probability.
It seems from preliminary results that the problem occurs on Mac but I never saw it yet on linux.

In the branch I'm trying to increase also the debugging output

**Comment by giovannipizzi** [comment]
In [this set of tests](https://github.com/giovannipizzi/disk-objectstore/actions/runs/165052334) I always instead get an error when reading an object that is loose.
Either in the first part, with errors like
` WARNING!!! ab1c875bce9fbdbd8ae815fdc380e9ea9d276025a5f8173735028fa7b5e5c43c is b'' (<class 'bytes'>); {'type': 'loose', 'size': 0, 'pack_id': None, 'pack_compressed': None, 'pack_offset': None, 'pack_length': None}`
or in the second part (with `get_object`) with errors like 
`WARNING!!! 301608b9bd8a36b6e83e2ed941c0ea45150708d5620987d1caa7491a98776000 is b'' (<class 'bytes'>)`

**Comment by giovannipizzi** [comment]
After re-running I got only one error that seems to confirm that the error comes from the packing:
```
WARNING!!! a5894e7c80a68cf5508acfb20ebe9a022c2de9bd0e3cdec7c706e5dac7887c92 is b'' (<class 'bytes'>); {'type': 'loose', 'size': 0, 'pack_id': None, 'pack_compressed': None, 'pack_offset': None, 'pack_length': None}
|-> AFTER RE-READING: checksum=a5894e7c80a68cf5508acfb20ebe9a022c2de9bd0e3cdec7c706e5dac7887c92, meta={'type': 'packed', 'size': 713, 'pack_id': 0, 'pack_compressed': False, 'pack_offset': 40151, 'pack_length': 713}
`-> CONTENT: b'^\xc3\x1dr\xe9dBz\x92\x9f\xf6{\xcf\x1d\x18\x0bu/\xe7.\x9b\xd6\xeb4J\'B\xccp\xbe\x13\xef\x1f\t\x95|\xed\xccph49.L{2\x11V\xb7\xac\xe7\xbf\xe2\xe2@~\xee-\xf5\x94NI0\x0c\xdd\xdbBNp\x8fP\xa4A\xb2\xd0\xf4\x1d\x96\xd8\xffF\x943A\xb3\xbaP\xf5\xb1j\x17\t\xb1M\xd9;\xec\xce\xf6\x87\x9b\xae\xba\xef\x84\xac\xfds;\xbe\xcegyb\xc7\xb5%ay\x93\xc9\x8cQ\xc0\xa6k\xdf\xc9s~\xf2>\xfd&N\xc3q-\xd2\xe6W\xcf\xfc\x8b<\x1d\xfa\x05\xd9\xff\xbf\x8f9\xf4\xf2uT\xc6\x0f{\xef8[i\xf4\'\xc8\x99:@\xe3Pq\x8c\xf3w\xedrZ\x01Z\xa6(#[\x13\x06\x0f9\xd2:\xfc\x05\x16kx\xedA\xee\x16\xa2\x88\x9d#\x0b,\xf1\xe4\x89\xcd\xae\x97-\x9e\xbe\xd4w\x97\xc6\x835\xf53\xf2d\r\xd2reW\xd0\xfe\xb3\x9epI\xd0\x98\xb9&=\xdegV\xc8\x87j\xef\xe1j6\xfc@K\xd1hr\x8b[\xd5\x195\x1d\xf7\xe3\x8e\x88^}\xe1\x04\x8a\x91W\x1e-p\xb8t:#e\xfc\'\x85\xf3\xd7Q=\x86\xe6-2\xef\x0c\xce\x91\xd7F\x04\xb1\x03!\x9evT=\xc1Tep2\xf3\x8dD\rE4~\xc6:\xcf\x07\x03D\xdev\xcf\'\x1fk\xbd\xc3\xef\x98C@\xca\x9f\xed\x02\xf2H\xd0\x9d2\xc8\x8c\x84\xef;\x9fN\xcb \xb0\x8f]\x91\xc6\xf5\xcap\xd8M\x14\xd6\x05\xc9\xb8\xae\xb8\x95\xf3\x13\x9e\x8e\xd4\xc9\xbb\x12\x87\xe0\xd7{\xef[\xb9\x80\x030vX\xa7P\'\x7f\x86f\xcf\xeal\xb1]\xe6\x92p\xde\x94\x1ab\x9bZa\xed?u\x1cY]\x85\xb8\x02C\x94\xe6`\n\x1ct\xd7\x84\xd1i\xdc\xe0K\x7f\x06\xdc\xe2\xba\x95\xa0m\x98A\x9fp\x0c\x81\x97d\xac\x04,\xc4\x90\x0c\xe7U\xf7\xe9\x94\xbb\x9c\x08g/${#5\xaaN\x8dh\xec5L|\x1f\r@\xd20\xf9T\xc12Y\x8c\x85\xeb\xb2\xf7V\xbb\x01Y\xa9\x89\x88\xfdR\x87\xc8\xcc1\xfd\x1cu\xee\x03]\xcch\x9b\xcf}\xa3\xe0\xcd\xcc\xac\x1b\xfc\xd3\x92\xc2b\xc8\xf10 \x8f\xdc\x1ajl\xb9\x08 \xff\xbe\xd5\xf1 \xf1\x18\n\xd4lfd"\xd0:|\'\xabnR\xd6]Oyv\x93\xff\\\xe2Uj\xde\x18\x1c\xc9m;3\xd8d\x00~\xba\x1c\x10\xc2\xbfi~M(\x12L\x12\xb3Gp` \xab}\xfe\xc2\x08o\x1f\x85\xfaQ\xc1\xb7\xa8_\x1dr\xd3\x82\xaf\xa9\x10\x8c\x98\x1f~\x17\xf8\xfa\xaa\xb4\x02]\x11V\xefD\xafkbvS\x11\x8a\x9bY\x8b\xb2\xf0\xf7t\xa40\xd1\n\xbb\xe9\xc3$\xbf\xa9\x9f\xbd\xb4\'\x11L\xc1\xccLm\xa0CA\xbc\x12\xa8\xbf\xf1\xf87j\r%f\x9a\x1a\xd4\x94w\xb7\xe5\xbb=~I\x82G\x1c\xa0\xe1\xf8({\xee\x81\x13W\x1d6O6'
```

In the second read, the content indeed has been packed correctly and matches its sha256 that is `a5894e7c80a68cf5508acfb20ebe9a022c2de9bd0e3cdec7c706e5dac7887c92`

**Comment by giovannipizzi** [comment]
I think I managed to finally reproduce the problem on my Mac. 
You need to write three scripts:

## test-conc-replace.py
```python
import os
import psutil

dest_fname = 'DEST.txt'
for i in range(10000):
    this_fname = str(psutil.Process().pid) + '.txt'
    with open(this_fname, 'wb') as fhandle:
        fhandle.write(b'CONTENT')
    try:
        os.replace(this_fname, dest_fname)
    except PermissionError:
        with open(dest_fname, 'rb') as f2:
            print(f2.read())
        raise
    print(this_fname, i)
```

## test-conc-delete.py
```python
import os
import psutil

dest_fname = 'DEST.txt'
for i in range(100000):
    if os.path.exists(dest_fname):
        os.remove(dest_fname)
        print(dest_fname, i, 'DELETED')
    else:
        print(dest_fname, i, 'continue')
```

## test-conc-read.py
```python
import os
import psutil

dest_fname = 'DEST.txt'
for i in range(100000):
    try:
        with open(dest_fname, 'rb') as fhandle:
            content = fhandle.read()
            assert content == b'CONTENT', 'FOUND INSTEAD: {}'.format(content)
        print(i, content)
    except FileNotFoundError:
        print(i, ">> DELETED <<")
```

Now, run them all at the same time.
I expect that the first keeps trying to replace the file with the content `CONTENT`. The second keeps trying to delete it.
This would be a problem in Windows (see #43) but not on Mac.

Therefore, I expect that if all operations are atomic, the reader either does not find the file, or finds a content `CONTENT`. Instead, when I run it, the reader often fails with:
```
AssertionError: FOUND INSTEAD: b''
```
That I think is the issue above.

Guess: on Mac, a `remove` first truncates the file and then removes it, making it non-atomic?

**Comment by giovannipizzi** [comment]
On Mac a simple solution would be to introduce the concept of a trash folder, and rename the object in there,without unlinking (otherwise you end up with the same issue). This wouldn't work anyway for windows, though (#37). 

I'm starting to think that the easiest thing to do is to simply don't delete loose objects while packing (this might be good also for data safety, in case something bad happens during packing, even if I never saw yet such a case). 

Duplicate loose files could be deleted at the next packing operation (which is already implemented, and ok as long as the second packing is done late enough so that all loose objects are not open anymore) and this should solve also (most) windows issues.

Or even better delegate this to maintenance operations that only should be operated while the container is not in use.

**Comment by giovannipizzi** [comment]
Actually the replace has nothing to do. The problem is just the remove/unlink.

The plots of the timing of the various parts of he code above in three cases are shown here, and as you can see in all runs there is always at least one deletion happening exactly during the read.

![example1](https://user-images.githubusercontent.com/16132028/87256247-3400ef80-c491-11ea-929d-4df0e1ae6dbc.png)
![Figure_1](https://user-images.githubusercontent.com/16132028/87256250-35321c80-c491-11ea-8beb-7e9ab1cf6309.png)
![Figure2](https://user-images.githubusercontent.com/16132028/87256252-35cab300-c491-11ea-8f9a-cfd71c0e8c1a.png)

Indeed the same exception can be obtained by simply running `test-conc-delete.py` and the following modified `test-conc-read.py`:
```python
import os
import psutil
import time

dest_fname = 'DEST.txt'
for i in range(100000):
    try:
        print("BE", time.time())
        with open(dest_fname, 'rb') as fhandle:
            print("IN", time.time())
            content = fhandle.read()
            print("AF", time.time())
            assert content == b'CONTENT', 'FOUND INSTEAD: {}'.format(content)
        print(i, content)
    except FileNotFoundError:
        print(i, ">> DELETED <<")
        # Recreate the file
        with open(dest_fname, 'wb') as fhandle:
            fhandle.write(b'CONTENT')
```

**Comment by giovannipizzi** [comment]
As a note, running this on Linux (Ubuntu, EXT4) has a lot of overlapping `open` and `delete` but never shows this problem.

See for instance this figure below.

![Figure_1](https://user-images.githubusercontent.com/16132028/87256453-09b03180-c493-11ea-8791-15c06ee576b5.png)

**Comment by giovannipizzi** [comment]
As a follow up, even if probably this is less critical for this library, I created a repo to reproduce the problem (that happens even in C): https://github.com/giovannipizzi/concurrent-delete-race-problem
and I also reported this to python: https://bugs.python.org/issue41291
